enableCloudNetSupport: false
lobbySwitcher:
  fillerItem:
    type: OUTLINE
    item:
      material: GRAY_STAINED_GLASS_PANE
  lobbyItem:
    types:
      NORMAL:
        material: GREEN_STAINED_GLASS
      EMPTY:
        material: GRAY_STAINED_GLASS
      UNREACHABLE:
        material: RED_STAINED_GLASS
  lobbyServers:
    - id: lobby2
      name: Lobby-2
      serverName: Lobby-2
teleporter:
  fillerItem:
    type: FULL
    item:
      material: GRAY_STAINED_GLASS_PANE
  servers:
    - id: oneblock
      name: OneBlock
      description: Player OneBlock with your friends
      item:
        material: PLAYER_HEAD
        texture: eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvYzQ3ZjIwMTgxNWMyYWI1Y2RmZWUwZmEyOTIyNTJlOGE5YmU2YWM2Y2FmMmIyODRiNDlkODc2ZGVjMDlmZWYxMSJ9fX0=
        slot: 10
      serverName: OneBlock
    - id: pvp
      name: PVP
      description: Battle other players
      item:
        material: DIAMOND_SWORD
        glowing: true
        slot: 11
      serverName: PVP
    - id: potionWars
      name: PotionWars
      description: Battle other players with potions
      item:
        material: POTION
        potion: DAMAGE_RESISTANCE
        amount: 5
        slot: 12
      serverName: PotionWars
    - id: helmetWars
      name: HelmetWars
      description: Battle other players with op helmets
      item:
        material: LEATHER_HELMET
        leatherColor: MAGENTA
        amount: 5
        slot: 13
      serverName: HelmetWars
    - id: spawn
      name: Spawn
      description: Teleport to the spawn
      item:
        material: BEACON
        slot: 16
      location: [ 0,80,0 ]