name: LogicLobby
version: '${project.version}'
main: de.frinshhd.logiclobby.Main
api-version: '1.19'
author: FrinshHD
softdepend: [ SuperVanish, PremiumVanish, CloudNet-Bridge ]

permissions:
  logiclobby.admin.updateNotify:
    default: op